cfg:
  model: RNN
  random_seed: 1204
  save_checkpoint: True
  log_to_wandb: True
  run_name: test
  resume: False
  run_id: null
  load_checkpoint: null

hyperparams:
  hidden_size: 128
  num_layers: 3
  batch_size: 32
  lr: 0.002
  num_epochs: 10