program: train_sweep.py
name: mixup-sweep
method: grid
metric:
  goal: maximize
  name: valid_f1
parameters:
  split:
    value: version
  model:
    value: RNN
  num_epochs:
    value: 25
  mlp_hidden_size_multiplier:
    value: 1.5
  adv_grad_multiplier:
    value: 0.02
  adv_grad_iter:
    value: 2000
  train_singing:
    value: False
  mixup_prob:
    values: [0.2, 0.4, 0.6, 0.8, 1.0]
  mixup_alpha:
    values: [0.1, 0.3, 0.5, 0.7]