cfg:
  model: RNN
  split: version
  random_seed: 1204
  train_singing: false
  save_checkpoint: True
  log_to_wandb: True
  run_name: test
  resume: False
  run_id: null
  load_checkpoint: null

hyperparams:
  hidden_size: 128
  num_layers: 3
  batch_size: 32
  lr: 0.002
  num_epochs: 25
  adv_grad_multiplier: 0.01
  adv_grad_iter: 2000