cfg:
  model: CNN
  split: version
  random_seed: 1204
  train_singing: false
  save_checkpoint: True
  log_to_wandb: True
  wandb_project: ring-leitmotif
  run_name: test
  resume: False
  run_id: null
  load_checkpoint: null

hyperparams:
  include_none_class: false
  batch_size: 32
  lr: 0.002
  adv_lr_multiplier: 10
  num_epochs: 40
  mixup_prob: 0
  mixup_alpha: 0