cfg:
  model: BBox
  split: act
  random_seed: 1204
  train_singing: false
  save_checkpoint: true
  log_to_wandb: true
  wandb_project: ring-leitmotif
  run_name: test
  resume: false
  run_id: null
  load_checkpoint: null

hyperparams:
  include_none_class: false
  batch_size: 32
  lr: 0.002
  adv_lr_multiplier: 10
  num_epochs: 40
  mixup_prob: 0
  mixup_alpha: 0
  filmgen_emb: 64
  filmgen_hidden: 64
  attn_dim: 64
  attn_depth: 3
  attn_heads: 6
  apply_attn: true # for BBoxModel