cfg:
  model: RNN
  split: version
  random_seed: 1204
  train_singing: false
  save_checkpoint: True
  log_to_wandb: True
  wandb_project: ring-leitmotif
  run_name: test
  resume: False
  run_id: null
  load_checkpoint: null

hyperparams:
  batch_size: 32
  lr: 0.002
  adv_lr_multiplier: 10
  num_epochs: 40
  train_adv: false
  adv_grad_multiplier: 0.01
  adv_grad_iter: 2000
  mlp_hidden_size: default
  mixup_prob: 0
  mixup_alpha: 0
